### ISSUE TITLE
WiFi Initialization Fails. Doesn't connect. 

### ISSUE THREAD

**Issue by tkamaal** [loboris/ESP32_TFT_library#18]
I'm using ESP32_TFT_library on ESP32_Wrover_Kit V3. I was able to Demo TFT Display functionality on the  LCD without using WiFi. As a part of next step, I wanted to use WiFi so I followed the steps provided in README and made modifications using make menuconfig. I have provided WiFi SSID and WiFi Password. 

I get the following error upon flashing the code. 

W (2855) wifi : wifi nvs_open fail ret = 4353
E (2857) wifi : wifi_init 1410 ret = 4353
ESP_ERROR_CHECK failed : esp_err_t 0x1101 at 0x4014bde

CPU halted. 

By going through the source code, I wasn't able to figure out what the error code meant. I looked into the following files esp_err.h and esp_wifi.h.

**Comment by tkamaal** [comment]
![esp_wifi_error_image](https://user-images.githubusercontent.com/27974027/32400350-2e23151a-c0bc-11e7-84a6-6f6bf19b85eb.JPG)

I have highlighted the error message.

**Comment by loboris** [comment]
Sorry for the bug, it is fixed now.

**Comment by tkamaal** [comment]
Thank you @loboris
