### ISSUE TITLE
why chars are printed reversed?

### ISSUE THREAD

**Issue by amardhore** [loboris/ESP32_TFT_library#36]
Loboris, Thanks for writing this library. Its pretty nice.. 
I am using ST7735R with esp32. My issue is, all the chars are printed reversed. I am using your demo and TFT_print() to print the string on the screen.  I am not sure what is wrong with my setup. Thanks.
--
Amar

**Comment by jjfretired** [comment]
I'm having the same issue with the wrover kit v3 with the ILI9341 display.

**Comment by jjfretired** [comment]
The ILI9341 expects big endian and the esp32 board is little endian.  Their  may have to be a conversion to the file/image before it is sent to the displayed.  I have no solution at this time.

**Comment by jjfretired** [comment]
I changed #Define TFT_INVERT_ROTATION1 = 1 to 0 in tftspi.h and it printer correctly.

**Comment by amardhore** [comment]
@jjfretired It works for me too. I was tried changing the endianess in commands but did not work. Thank you for letting me know.
