### ISSUE TITLE
font_rotate = 0 issue.

### ISSUE THREAD

**Issue by juphaono** [loboris/ESP32_TFT_library#5]
Hi loboris,
I just got brand new WROVER_KIT V3 with LCD Type ST7789V. I have downloaded your library and everything works fine. I can see all the demos excepted the text print on the LCD.

I have found that when font_rotate = 0 then it can not print string on the screen.
Then I have tried setting font_rotate = 1 then the strings now being printed.

By the way, thank you for contributing the library.
//juphaono
![lcdissue](https://user-images.githubusercontent.com/15163340/30676739-95bab1ee-9e55-11e7-91bc-092b5cc5c606.jpg)

**Comment by loboris** [comment]
Could you, please, try with the latest commit and report if you still have this issue.

**Comment by juphaono** [comment]
Hi loboris,

Thank for correcting the issue. Now the LCD wor
![20171001_095436](https://user-images.githubusercontent.com/15163340/31055334-47e5fad6-a68f-11e7-9c0e-8869c80c639e.jpg)
ks and displays every demos perfectly.
